### ISSUE TITLE
Help with importing from xml file

### ISSUE THREAD

**Issue by Knuj0** [alexpung/UK-Investment-tax-calculator#40]
Hi, thought I'd leave a quick feedback from my experience
I have recently given the App a try but unfortunately it only Imports Dividends ignoring Futures and Stocks. Fact that it is importing Dividends makes me thing xml file is good and the problem is somewhere else. FYI: Section104.txt and Trades Calculations.txt are empty whereas Dividends Summeary.txt has been populated with correct details

**Comment by alexpung** [comment]
What is the number shown in the app just below the import section?

e.g.
Number of tax events: 45
Number of dividends imported: 10
Number of trades imported: 35
Number of corporate actions imported: 0

**Comment by Knuj0** [comment]
Number of tax events: 8
Number of dividends imported: 0
Number of trades imported: 0
Number of corporate actions imported: 0

**Comment by Knuj0** [comment]
sorry had a typo!
Number of tax events: 8
Number of dividends imported: 8
Number of trades imported: 0
Number of corporate actions imported: 0

**Comment by alexpung** [comment]
Then the trades are not imported.
Make sure your trades are in the same format as:
https://github.com/alexpung/UK-Investment-tax-calculator/tree/master/UnitTest/System%20Test/Interactive%20brokers


In particular levelOfDetail should be "ORDER"

<Order currency="USD" fxRateToBase="0.8" assetCategory="STK" symbol="ABC" description="ABC Example Stock" dateTime="01-May-21 12:34:56" quantity="200" proceeds="-2000" taxes="-20" ibCommission="-1.5" ibCommissionCurrency="USD" buySell="BUY" levelOfDetail="ORDER" />

**Comment by Knuj0** [comment]
This is the format I am using: 
I have 2 doubt: my  DateTime format (in particular HH:MM:SS) and levelOfDetail is sometimes "EXECUTION" (not sure why as they are trades anyway)

<Order currency="EUR" fxRateToBase="0.84561" assetCategory="STK" symbol="EFRN" description="ISHARES EURO FLOATING RATE B" dateTime="20-May-22 112234" quantity="2228" proceeds="-11095.44" taxes="0" ibCommission="-5.54772" ibCommissionCurrency="EUR" buySell="BUY" levelOfDetail="ORDER"/>
<Trade currency="EUR" fxRateToBase="0.84561" assetCategory="STK" symbol="EFRN" description="ISHARES EURO FLOATING RATE B" dateTime="20-May-22 112234" quantity="2228" proceeds="-11095.44" taxes="0" ibCommission="-5.54772" ibCommissionCurrency="EUR" buySell="BUY" levelOfDetail="EXECUTION"/>

**Comment by Knuj0** [comment]
![Screenshot 2023-12-29 162943](https://github.com/alexpung/UK-Investment-tax-calculator/assets/155073441/4662e382-c8cc-4ce3-86ae-900a58d74fc1)

**Comment by alexpung** [comment]
It should work if you correct the time format.

The app is a bit of pain when an exception occurs. It just swallow the error and give the error at the browser console.
System.FormatException: Format_BadDateTime, 20-May-22 112234

Thanks for the feedback.

**Comment by Knuj0** [comment]
great! it looks like that by changing the time format I get many more trades - I understand Options are not being imported (IBKR Classes: Equity and Index Options, Options on Future, Warrants) and same for Bonds and other Fixed Income instruments.  I'd like to check and compare calculations , is there a way to download Calculations/Reposts in csv format? Thank you!

**Comment by alexpung** [comment]
In the Disposal calculation summary page you can export the table to excel or pdf, but the details are hidden.

**Comment by Knuj0** [comment]
thank you very much - do you plan to implement  Equity and Index Options, Options on Future, Warrants also - their calculations mimic stocks though you'd need to deal with options exercises events ? will you keep only  the app or have also a python local version?

**Comment by alexpung** [comment]
I may consider implementing options someday but not in the near future.
