### ISSUE TITLE
Capital Gain calculations for Futures

### ISSUE THREAD

**Issue by Knuj0** [alexpung/UK-Investment-tax-calculator#41]
I have run a couple of tests using futures trades and have noticed that in the output pdf  all closing trades for Gain/Loss calculation are classified  as SELL .
I would expect to see  2 type of trades:
SELL : a buy order matched with a sell order at a later time
Close_Shorts: a buy order matched with a buy order at a later time

It could be just a question of naming the closing trades but if not then I think it might be returning the wrong sterling pnl as the fx rate to be used is from the date of the Closing Trade (which as I said above can be either a buy or a sell order depending on the sequence of events)

**Comment by alexpung** [comment]
It should just be classified as a SELL (as a disposal of a future contract) internally.

Please refer to the text file for a more accurate description. It would say Close long position/Close short position

e.g.
Disposal 14: Close long position 1 units of NIYZ2 on 21-Sep-2022.	Total gain (loss): -£4.95
Trade details:
	Sold 1 unit(s) of NIYZ2 on 21-Sep-2022 22:40 with contract value ¥13,415,000 with total expense £2.48
	Expenses: Commission: ¥397 = £2.48 Fx rate = 0.0062401	
Trade matching:
Same day: Matched 1 units of the disposal. Acquisition contract value is ¥13,415,000 and disposal contract value is ¥13,415,000
Payment received to close the contract as gain is (¥13,415,000 - ¥13,415,000) * 0.0062401 = £0.00, added to disposal proceed.
Total dealing cost is £4.95
Matched trade: Bought 1 unit(s) of NIYZ2 on 21-Sep-2022 22:25 with contract value ¥13,415,000 with total expense £2.48
	Expenses: Commission: ¥397 = £2.48 Fx rate = 0.0062401	
Gain for this match is £0.00 - £4.95  = -£4.95

From my interpretation of the law:

1. There is no shorting in the realm of future contracts. Opening a short position is considered an acquisition of a short contract.
2. The margin payments do not affect the calculations. The profit and loss is only realised when the contract is closed by computing the difference in contract value and the fx rate used is the rate when the position is closed.
3. The commission cost is computed using fx rate at the day it is incurred as usual.

**Comment by Knuj0** [comment]
gotcha! 
I was looking at the Disposal Summary as it is a PDF and I wanted to check the results as I thought it contained all futures trades gain/loss calculations!
Export Trades seems correct  but very hard to check calculations  as it is in a txt file. thank you again!
is the Futures calculations available in Python so I can try export result in a different format and check against my own calculations?

**Comment by Knuj0** [comment]
one more thing: why have you got 2 exports: one for Trades ad one for Section 104??? aren't all Section 104 included in Trades?

**Comment by alexpung** [comment]
The future trade calculation is only available in this project. There is an old project written in Python but that don't support future contracts.

As for why there is "Trades" and "Section 104", one shows the matching for each disposal and one show the section 104 pool accumulation/withdrawal. They are intended to complement each other to show the calculations.

**Comment by Knuj0** [comment]
understood .
 in the meantime I am checking a few simple closed trades but the results/calculations seem wrong and I am not sure what happens inside the calculation engine 
I am posting it here  for you to have a look and investigate further
this is from IBKR xlm:
Symbol Date/Time Quantity T. Price C. Price Proceeds Comm/Fee Basis Realized P/L Realized P/L % MTM P/L Code
SO3M4 2022-09-28, 05:12:27 -1 94.0750 94.5650 235,187.50 -1.70 -235,185.80 0.00 0.00 -1,225.00 O
SO3M4 2022-09-28, 06:34:35 1 94.0750 94.5650 -235,187.50 -1.70 235,185.80 -3.40 0.00 1,225.00 C
SO3M4 2022-09-28, 07:26:40 -1 94.0000 94.5650 235,000.00 -1.70 -234,998.30 0.00 0.00 -1,412.50 O
SO3M4 2022-09-29, 10:50:54 1 94.4650 94.5050 -236,162.50 -1.70 234,998.30 -1,165.90 -0.50 100.00 C
Total SO3M4 0 -1,162.50 -6.80 0.00 -1,169.30 -0.25 -1,312.50

and this is from the app export trades:
Disposal 106: Close short position 1 units of SO3M4 on 28-Sep-2022.	Total gain (loss): -£3.40
Trade details:
	Bought 1 unit(s) of SO3M4 on 28-Sep-2022 06:34 with contract value £235,187.50 with total expense £1.70
	Expenses: Commission: £1.70	
Trade matching:
Same day: Matched 1 units of the disposal. Acquisition contract value is £235,187.50 and disposal contract value is £235,187.50
Payment received to close the contract as gain is (£235,187.50 - £235,187.50) * 1 = £0.00, added to disposal proceed.
Total dealing cost is £3.40
Matched trade: Sold 1 unit(s) of SO3M4 on 28-Sep-2022 05:12 with contract value £235,187.50 with total expense £1.70
	Expenses: Commission: £1.70	
Gain for this match is £0.00 - £3.40  = -£3.40

Disposal 122: Close short position 1 units of SO3M4 on 29-Sep-2022.	Total gain (loss): £1,159.10
Trade details:
	Bought 1 unit(s) of SO3M4 on 29-Sep-2022 10:50 with contract value £236,162.50 with total expense £1.70
	Expenses: Commission: £1.70	
Trade matching:
At time of disposal, section 104 contains 1 units with contract value £235,000.00
Section 104: Matched 1 units of the disposal. Acquisition contract value is £235,000.00 and disposal contract value £236,162.50, proportioned dealing cost is £1.70
Payment received to close the contract as gain is (£236,162.50 - £235,000.00) * 1 = £1,162.50, added to disposal proceed.
Total dealing cost is £3.40
Gain for this match is £1,162.50 - £3.40  = £1,159.10

so first closing trade gain/loss matches , but second closing trade is wrong , the app returns a gain whereas it is a loss!

**Comment by alexpung** [comment]
I have pushed a fix on that. Nice catch.
